Cases query
projectcaluma/ember-caluma pull request #1048
Opened 2020-09-29 18:34 UTC by velrest

2020-09-30 08:08 UTC, anehx requested changes
Code looks good but documentation is inadequate, please fix that.

2020-09-30 08:08 UTC, anehx commented on addon/caluma-query/queries/base.js
> +    queryOptions = {},
This needs to be documented

2020-09-30 08:08 UTC, anehx commented on addon/caluma-query/queries/index.js
> +export function allCases(options) {
Document it...

2020-10-01 06:24 UTC, velrest commented on addon/caluma-query/queries/base.js
> +    queryOptions = {},
Done :+1:

2020-10-01 06:24 UTC, velrest commented on addon/caluma-query/queries/index.js
> +export function allCases(options) {
Also done

2020-10-01 06:41 UTC, anehx commented
Now we still have failing tests

2020-10-02 16:08 UTC, velrest commented
@anehx should be fixed now

2020-10-05 08:36 UTC, anehx approved these changes

2020-10-05 09:19 UTC, merged