feat(cfb): mark conditionally required / hidden questions
projectcaluma/ember-caluma pull request #1445
Opened 2021-06-16 09:16 UTC by luytena

Enhance question type markers in question list of form-
builder with additional styles for conditionally required
and hidden JEXL expressions.

Resolves: #1306

2021-08-06 14:48 UTC, luytena commented
@anehx Some design options, I find the striped versions a bit hard to read. Any preferences or ideas?
![image](https://user-images.githubusercontent.com/32454507/128523278-2e306c59-450e-44bb-9c84-cc6fd7a92234.png)
![image](https://user-images.githubusercontent.com/32454507/128523707-d5658a32-a20a-462b-aa05-a286b0900bba.png)
![image](https://user-images.githubusercontent.com/32454507/128523938-6cc733d4-32f7-4ce6-adaa-db35a971b959.png)
![image](https://user-images.githubusercontent.com/32454507/128527779-50a183ab-aeec-4a4f-8970-bd6d9d6cd858.png)

2021-08-10 07:22 UTC, luytena commented
@anehx Added your suggestions, now looks like this:
![image](https://user-images.githubusercontent.com/32454507/128825253-d489e8a0-e96e-4685-8c50-890debe70544.png)

2021-08-10 09:29 UTC, anehx requested changes
Some nitpicks about CSS, otherwise looks very good. Good work! :100:

2021-08-10 09:29 UTC, anehx commented on addon/components/cfb-form-editor/question-list/item.hbs
> +      }}
Put this into JS code

2021-08-10 09:29 UTC, anehx commented on addon/components/cfb-form-editor/question-list/item.hbs
> +            class="uk-position-top-right cfb-form-editor__question-list__item__required-{{requiredType}}"
```suggestion
            class="uk-position-top-right cfb-form-editor__question-list__item__required cfb-form-editor__question-list__item__required--{{requiredType}}"
```

`ember-caluma` uses [BEM](http://getbem.com) as CSS convention. Feel free to ask me about it if you want to know more - it's hard to put it into a comment :wink:

2021-08-10 09:29 UTC, anehx commented on app/styles/cfb-form-editor/question-list/_item.scss
> +.cfb-form-editor__question-list__item__required-required {
```suggestion
.cfb-form-editor__question-list__item__required {
```

2021-08-10 09:29 UTC, anehx commented on app/styles/cfb-form-editor/question-list/_item.scss
> +}
Drop this

2021-08-10 09:29 UTC, anehx commented on app/styles/cfb-form-editor/question-list/_item.scss
> +.cfb-form-editor__question-list__item__required-conditional::after {
```suggestion
.cfb-form-editor__question-list__item__required--conditional::after {
```

2021-08-10 09:29 UTC, anehx commented on app/styles/cfb-form-editor/question-list/_item.scss
> +  color: darken($global-muted-color, 30%) !important;
```suggestion
  color: $global-color;
```

2021-08-10 11:52 UTC, anehx requested changes

2021-08-10 11:52 UTC, anehx commented on addon/components/cfb-form-editor/question-list/item.hbs
> +          class="{{if this.hidden (concat "cfb-form-editor__question-list__item__hidden")}} cfb-form-editor__question-list__item__type"
```suggestion
          class="cfb-form-editor__question-list__item__type {{if this.hidden "cfb-form-editor__question-list__item__type--hidden"}} "
```

2021-08-10 11:52 UTC, anehx commented on addon/components/cfb-form-editor/question-list/item.hbs
> +        <UkBadge
Indent is incorrect

2021-08-10 11:52 UTC, anehx commented on app/styles/cfb-form-editor/question-list/_item.scss
> +}
```suggestion

  &--conditional::after {
    content: "";
    transform: translate(3px, 3px);
    width: 3px;
    height: 3px;
    background: $global-background;
    border-radius: 50%;
    display: block;
  }
}
```

2021-08-10 11:52 UTC, anehx commented on app/styles/cfb-form-editor/question-list/_item.scss
>  }
```suggestion

  &--hidden {
    background-color: $global-background;
    color: $global-color !important;
  }
}
```

2021-08-10 12:17 UTC, luytena commented
@anehx Thanks for the reviews, learnt a few new things about css and scss :D

2021-08-10 13:09 UTC, anehx commented
> @anehx Thanks for the reviews, learnt a few new things about css and scss :D

Good! Looks very clean now, awesome work! :fire:

2021-08-10 13:09 UTC, anehx approved these changes

2021-08-10 13:09 UTC, merged

2021-08-11 06:48 UTC, anehx commented
:tada: This PR is included in version 7.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ember-caluma/v/7.5.0)
- [GitHub release](https://github.com/projectcaluma/ember-caluma/releases/tag/v7.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: