W.I.P. analytics module for caluma
projectcaluma/ember-caluma pull request #1655
Opened 2021-11-22 13:08 UTC by derrabauke

Includes a demo implementation which is reachable from the demo menu.

- [x] List of existing analytics tables
- [x] Form to build & edit the analytics table
- [ ] Preview of table contens
- [ ] Pivot tables

2022-05-05 09:28 UTC, velrest commented
@derrabauke feel assigned as reviewr

2022-05-05 14:01 UTC, Yelinz requested changes
Also lots of `todo` in the tests

2022-06-01 13:59 UTC, velrest commented on packages/analytics/addon/components/ca-field-form.js
> +  updateAnalyticsField(field) {
Removed

2022-06-01 14:06 UTC, velrest commented on packages/analytics/translations/fr.yaml
> +    back: Back to the list
done, deepl

2022-06-01 14:11 UTC, velrest commented on packages/analytics/config/ember-try.js
> -../../../config/ember-try.js
The other packages also use independent config files. not sure if this is supposed to be like this or not.

2022-06-01 14:14 UTC, velrest commented on packages/analytics/addon/templates/reports/new.hbs
> +  <CaReportBuilder @analyticsTable={{this.data.value}} />
done

2022-06-01 14:36 UTC, velrest commented on packages/analytics/addon/routes/reports.js
> +export default class ReportsRoute extends Route {}
Removed

2022-06-01 14:37 UTC, velrest commented on packages/analytics/addon/components/ca-toggle-switch.hbs
> +      @on-toggle={{@update}}
done

2022-06-01 14:39 UTC, velrest commented on packages/analytics/addon/components/ca-field-select.hbs
> +    @loadingMessage="Loading..."
Removed since powerselect has no isloading param i found and cant infer the loading state based on the on open trigger

2022-06-01 14:53 UTC, velrest commented on packages/analytics/addon/components/ca-field-select.js
> +    this.fetchOptions.perform();
Removed

2022-06-01 14:59 UTC, velrest commented on packages/analytics/addon/components/ca-field-selector-list/ca-field-alias-input.hbs
> +  ></button>
done

2022-06-01 15:10 UTC, velrest commented on packages/analytics/addon/templates/reports/edit.hbs
> +      ></button>
done, used `name=` since the button element has no actual title attribute.

2022-06-01 15:11 UTC, velrest commented on packages/analytics/addon/templates/reports/edit.hbs
> +      ></button>
Or at least i havn't found one

2022-06-01 15:14 UTC, velrest commented on packages/analytics/addon/validations/field.js
> +  // TODO: add other field properties
Whoa didnt know this file existed

2022-06-01 15:15 UTC, velrest commented on packages/analytics/addon/controllers/reports/new.js
> +export default class ReportsNewController extends Controller {}
removed

2022-06-01 15:17 UTC, velrest commented on packages/analytics/addon/components/ca-field-selector-list.hbs
> +            ></button>
done

2022-06-01 15:17 UTC, velrest commented on packages/analytics/addon/components/ca-filter-modal.hbs
> +          ></button>
done

2022-06-01 15:22 UTC, velrest commented on packages/analytics/addon/components/ca-field-selector-filter.hbs
> +        </button>
removed, component was actually not needed anymore

2022-06-01 15:47 UTC, velrest commented on packages/analytics/addon/validators/filter.js
> +      // TODO: implement deep validations
Deleted the filter validator since the form has no filter field.

2022-06-01 15:47 UTC, velrest commented on packages/analytics/addon/validations/field.js
> +  // TODO: add other field properties
Removed todo and filter field

2022-06-02 09:11 UTC, Yelinz commented on packages/analytics/addon/components/ca-filter-modal.hbs
> +{{yield (component "uk-button" onClick=(fn (mut this.visible) true))}}
Im not well versed in this topic @anehx might be able to explain better, but afaik it has something to do with this https://github.com/embroider-build/embroider/blob/main/REPLACING-COMPONENT-HELPER.md
But i think this is ok

2022-06-02 09:31 UTC, Yelinz commented on packages/analytics/config/ember-try.js
> -../../../config/ember-try.js
https://github.com/projectcaluma/ember-caluma/blob/main/packages/form-builder/config/ember-try.js
https://github.com/projectcaluma/ember-caluma/blob/main/packages/workflow/config/ember-try.js
The others use soft links to the same config, like it was here

2022-06-02 10:46 UTC, velrest commented on packages/analytics/config/ember-try.js
> -../../../config/ember-try.js
ah fair point, didnt know, git is able to softlink

2022-06-02 10:48 UTC, velrest commented on packages/analytics/config/ember-try.js
> -../../../config/ember-try.js
done

2022-06-02 10:48 UTC, velrest commented on packages/analytics/testem.js
> -../../config/testem.js
Done

2022-08-02 07:50 UTC, merged

2022-08-02 09:17 UTC, anehx commented
:tada: This PR is included in version @projectcaluma/ember-core-v11.0.0-beta.8 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@projectcaluma/ember-core/v/11.0.0-beta.8)
- [GitHub release](https://github.com/projectcaluma/ember-caluma/releases/tag/%40projectcaluma/ember-core-v11.0.0-beta.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-02 09:25 UTC, anehx commented
:tada: This PR is included in version @projectcaluma/ember-form-builder-v11.0.0-beta.15 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@projectcaluma/ember-form-builder/v/11.0.0-beta.15)
- [GitHub release](https://github.com/projectcaluma/ember-caluma/releases/tag/%40projectcaluma/ember-form-builder-v11.0.0-beta.15)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: