fix(form): fix dependencies for ember-autoresize-modifier
projectcaluma/ember-caluma pull request #1742
Opened 2022-01-10 08:34 UTC by JohnL17

2022-01-10 09:53 UTC, anehx requested changes
This needs to be added to the blueprint as well.

2022-01-10 12:35 UTC, JohnL17 commented
> This needs to be added to the blueprint as well.

Is it ok like this?

2022-01-10 12:49 UTC, anehx approved these changes

2022-01-10 12:49 UTC, merged

2022-01-18 17:24 UTC, anehx commented
:tada: This PR is included in version @projectcaluma/ember-form-v11.0.0-beta.2 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@projectcaluma/ember-form/v/11.0.0-beta.2)
- [GitHub release](https://github.com/projectcaluma/ember-caluma/releases/tag/%40projectcaluma/ember-form-v11.0.0-beta.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: