feat(distribution): add functionality to send all pending inquiries
projectcaluma/ember-caluma pull request #1862
Opened 2022-03-14 13:13 UTC by anehx

2022-03-22 16:30 UTC, luytena requested changes

2022-03-22 16:30 UTC, luytena commented on packages/distribution/addon/components/distribution-navigation.js
> +          [key]: this.scheduler.groupCache.length
Add comment

2022-03-23 09:22 UTC, anehx commented on packages/distribution/addon/services/distribution.js
> +    });
Done

2022-03-23 09:22 UTC, anehx commented on packages/distribution/addon/components/distribution-navigation.js
> +          [key]: this.scheduler.groupCache.length
Done

2022-03-23 12:22 UTC, luytena approved these changes

2022-03-23 12:22 UTC, merged

2022-03-24 09:37 UTC, anehx commented
:tada: This PR is included in version @projectcaluma/ember-distribution-v1.0.0-beta.6 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@projectcaluma/ember-distribution/v/1.0.0-beta.6)
- [GitHub release](https://github.com/projectcaluma/ember-caluma/releases/tag/%40projectcaluma/ember-distribution-v1.0.0-beta.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: