Embroider fixes
projectcaluma/ember-caluma pull request #1876
Opened 2022-03-22 10:56 UTC by anehx

This PR contains various fixes needed for embroider support - however, there are various other issues in dependencies that need to be resolved before we can fully support embroider. Pipeline status can be seen in #1873

2022-03-22 16:48 UTC, luytena requested changes

2022-03-22 16:48 UTC, luytena commented on packages/testing/addon/mirage-graphql/deserialize.js
> +    // this is expected most times
Why?

2022-03-22 16:48 UTC, luytena commented on packages/testing/addon/mirage-graphql/deserialize.js
> +    // this is expected most times
Add comment

2022-03-23 09:17 UTC, anehx commented on packages/testing/addon/mirage-graphql/deserialize.js
> +    // this is expected most times
Done

2022-03-23 11:55 UTC, luytena approved these changes

2022-03-23 12:22 UTC, merged

2022-03-23 13:40 UTC, anehx commented
:tada: This PR is included in version @projectcaluma/ember-testing-v11.0.0-beta.5 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@projectcaluma/ember-testing/v/11.0.0-beta.5)
- [GitHub release](https://github.com/projectcaluma/ember-caluma/releases/tag/%40projectcaluma/ember-testing-v11.0.0-beta.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: