fix(analytics): update startingOptions to reflect schema
projectcaluma/ember-caluma pull request #2096
Opened 2022-08-25 15:41 UTC by Yelinz

## Description

Add `DOCUMENTS` and `WORK_ITEMS` startingOptions to reflect the schema

2022-08-26 09:34 UTC, anehx requested changes

2022-08-26 09:34 UTC, anehx commented on packages/analytics/addon/components/ca-report-builder.js
> +      { label: "Documents", value: "DOCUMENTS" },
This needs to be translated

2022-08-26 14:46 UTC, Yelinz commented on packages/analytics/addon/components/ca-report-builder.js
> +      { label: "Documents", value: "DOCUMENTS" },
added translations

2022-08-29 06:17 UTC, anehx requested changes

2022-08-29 06:17 UTC, anehx commented on packages/analytics/translations/de.yaml
> +      cases: Fälle
Let's use "Dossiers"

2022-08-31 05:46 UTC, Yelinz commented on packages/analytics/translations/de.yaml
> +      cases: Fälle
Done

2022-08-31 07:08 UTC, anehx approved these changes

2022-08-31 07:08 UTC, merged