fix(cfb): fix min, max being invalid when empty
projectcaluma/ember-caluma pull request #2221
Opened 2022-11-24 16:17 UTC by Yelinz

## Description

Integer questions currently can't be saved without setting a min and max value, because the validation deems undefined an invalid value

2022-11-28 09:46 UTC, anehx requested changes
Why didn't you do that in the validation definitions for the models? We might not want this everywhere..

2022-11-30 09:31 UTC, Yelinz commented
Changed

2022-11-30 09:50 UTC, anehx commented on packages/form-builder/addon/validators/gt-lt.js
> +    return validateNumber(parsedOptions)(key, newValue);
Why this?

2022-12-20 10:42 UTC, anehx approved these changes

2022-12-20 12:28 UTC, merged